language: python
before_install:
  - pip install pep8
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pocketsphinx-python
install:
 - pwd
 - ls -lah
 - VIRTUALENV_ROOT=${VIRTUAL_ENV} ./mycroft-core/dev_setup.sh -sm
 - pip install -r mycroft-core/requirements.txt
 - pip install -r mycroft-core/test-requirements.txt
 - $VIRTUALENV_ROOT/msm install https://github.com/btotharye/mycroft-homeassistant.git
 
    
script:
 - pep8 __init__.py
 - ls $VIRTUAL_ENV
 - ls /opt/mycroft/skills
 - source $VIRTUALENV_ROOT/bin/activate
 - cp $TRAVIS_BUILD_DIR/mycroft-core/test/integrationtests/skills/skill_developers_testrunner.py /opt/mycroft/skills/mycroft-homeassistant
 - python /opt/mycroft/skills/mycroft-homeassistant/skill_developers_testrunner.py

env:
- IS_TRAVIS=true

after_success:
  coveralls
