language: python
before_install:
  - pip install pep8
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath
  - ls ~/virtualenv
python:
  - "3.6"

cache: pocketsphinx-python
install:
 - ./mycroft-core/dev_setup.sh -sm
 - pwd
 - echo $VIRTUALENV_ROOT
 - ls -lah $TRAVIS_BUILD_DIR/mycroft-core/.venv
 - pip install -r mycroft-core/requirements.txt
 - pip install -r mycroft-core/test-requirements.txt
 - source $TRAVIS_BUILD_DIR/mycroft-core/.venv/bin/activate
 - $TRAVIS_BUILD_DIR/mycroft-core/.venv/bin/msm install https://github.com/btotharye/mycroft-homeassistant.git
 - cp $TRAVIS_BUILD_DIR/mycroft-core/test/integrationtests/skills/skill_developers_testrunner.py /opt/mycroft/skills/mycroft-homeassistant.btotharye

 
    
script:
 - pep8 __init__.py
 - pwd
 - $TRAVIS_BUILD_DIR/mycroft-core/.venv/bin/python /opt/mycroft/skills/mycroft-homeassistant.btotharye/skill_developers_testrunner.py

env:
- IS_TRAVIS=true

after_success:
  coveralls
