language: python
before_install:
  - pip install pep8
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pocketsphinx-python
install:
 - pwd
 - ls -lah
 - VIRTUALENV_ROOT=${VIRTUAL_ENV} ./mycroft-core/dev_setup.sh
 - pip install -r $pwd/requirements.txt
 - pip install -r $pwd/test-requirements.txt
 - $pwd/mycroft/msm install https://github.com/btotharye/mycroft-homeassistant.git
 
    
script:
 - pep8 __init__.py
 - python /$pwd/test/integrationtest/skills/single_test.py /opt/mycroft/skills/mycroft-homeassistant.btotharye
