language: python
before_install:
  - pip install pep8
  - git clone https://github.com/MycroftAI/mycroft-core.git
  - sudo apt-get update -qq
  - sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath
  - ls ~/virtualenv
  - ./mycroft-core/dev_setup.sh -sm
  - pip install -r mycroft-core/requirements.txt
  - pip install -r mycroft-core/test-requirements.txt
  - source $TRAVIS_BUILD_DIR/mycroft-core/.venv/bin/activate
python:
  - "3.6"

cache: pocketsphinx-python
install:
 - pwd
 - echo $VIRTUALENV_ROOT
 - ls -lah $TRAVIS_BUILD_DIR/mycroft-core/.venv
 - ~/virtualenv/python3.6/bin/msm install https://github.com/btotharye/mycroft-homeassistant.git
 - chmod u+x test/run_test.sh
 - cp $TRAVIS_BUILD_DIR/mycroft-core/test/integrationtests/skills/skill_developers_testrunner.py /opt/mycroft/skills/mycroft-homeassistant.btotharye
 - cp -R $TRAVIS_BUILD_DIR/mycroft-core/test/integrationtests /opt/mycroft/skills/mycroft-homeassistant.btotharye/test
 
    
script:
 - pep8 __init__.py
 - python3 /opt/mycroft/skills/mycroft-homeassistant.btotharye/skill_developers_testrunner.py

after_success:
  coveralls
