version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            git clone https://github.com/MycroftAI/mycroft-core.git
            ls -lah $VIRTUAL_ENV
            pip install pep8
            cd mycroft-core
            sudo apt-get update -qq
            sudo apt-get install -qq mpg123 portaudio19-dev libglib2.0-dev swig bison libtool autoconf libglib2.0-dev libicu-dev libfann-dev realpath
            ./dev_setup.sh
            pip install -r requirements.txt
            pip install -r test-requirements
            cp mycroft-core/test/integrationtests/skills/skill_developers_testrunner.py /opt/mycroft/skills/mycroft-homeassistant.btotharye

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            $CIRCLE_WORKING_DIRECTORY/mycroft-core/venv/bin/activate
            pep8 mycroft test
            python /opt/mycroft/skills/mycroft-homeassistant.btotharye/skill_developers_testrunner.py
            
          
      - store_test_results:
          path: test-reports/
